#!/usr/bin/env python3
"""
Cross-Model Validation — Compare market simulator outputs against public reference trajectories.
================================================================================================
Compares our profit-driven market simulation results against published trajectories
from EIA AEO, NREL ReEDS Standard Scenarios, and EPA IPM to validate that the model
produces directionally consistent results under comparable assumptions.

This script is structure-only: no simulations are run. Pre-computed results are
loaded from disk (generated by a separate simulation run).

Usage:
    python -m pytest tests/validate_cross_model.py -v   # Run structure tests
    python tests/validate_cross_model.py                 # Run comparison (needs cached results)
"""

import json
import os
import sys
import unittest
from pathlib import Path

# ---------------------------------------------------------------------------
# 1. Hard-coded reference trajectories from publicly available sources
# ---------------------------------------------------------------------------
# NOTE: These are approximate values transcribed from published reports.
# They should be verified against the actual published tables before use
# in any formal validation. The exact numbers matter less than having the
# comparison structure in place.

AEO_REFERENCE = {
    'source': 'EIA Annual Energy Outlook 2025, Table 8',
    'url': 'https://www.eia.gov/outlooks/aeo/',
    'metric': 'clean_share_pct',  # renewables + nuclear as % of generation
    'national': {2025: 42, 2030: 47, 2035: 51, 2040: 54, 2050: 58},
    # Note: AEO is national, not ISO-specific. Use as directional benchmark.
    # AEO Reference assumes current policy only — no new climate legislation.
}

REEDS_MID = {
    'source': 'NREL Standard Scenarios 2024, Mid-Case',
    'url': 'https://www.nrel.gov/analysis/standard-scenarios.html',
    'metric': 'clean_share_pct',
    'national': {2025: 43, 2030: 52, 2035: 60, 2040: 67, 2050: 78},
    # ReEDS is cost-minimizing with RPS constraints — expect higher clean %
    # than AEO because it assumes cost-optimal deployment, not just current policy.
}

EPA_IPM_REF = {
    'source': 'EPA IPM v6 Reference Case (2023)',
    'url': 'https://www.epa.gov/power-sector-modeling',
    'metric': 'coal_share_pct',
    'national': {2025: 16, 2030: 12, 2035: 8, 2040: 5, 2050: 2},
    # IPM focuses on coal retirement under existing regulations.
    # Useful for validating our fossil dispatch / retirement logic.
}

ALL_REFERENCES = {
    'AEO_Reference': AEO_REFERENCE,
    'REEDS_Mid': REEDS_MID,
    'EPA_IPM_Ref': EPA_IPM_REF,
}

REQUIRED_REFERENCE_KEYS = {'source', 'metric', 'national'}

# ISOs in the market simulator
ISOS = ['CAISO', 'ERCOT', 'PJM', 'NYISO', 'NEISO', 'MISO', 'SPP']

# Default path for cached simulation results
SCRIPT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = SCRIPT_DIR.parent / 'data'
CV_RESULTS_PATH = DATA_DIR / 'cv_reference_results.json'


# ---------------------------------------------------------------------------
# 2. Helper functions — scenario parameter builders
# ---------------------------------------------------------------------------

def build_reference_scenario_params():
    """Return the conditions dict for a 'reference-equivalent' scenario.

    Maps to: Medium demand, Medium LCOE, Medium gas, $0 carbon price.
    This approximates the AEO Reference Case assumptions (current policy,
    no new carbon pricing) within our model's parameter space.
    """
    return {
        'name': 'CV_Reference_Zero_Carbon',
        'demand_growth': 'Medium',
        'lcoe_level': 'Medium',
        'fuel_level': 'Medium',
        'carbon_price': 0,
        'learning_rate': 'Medium',
        '45q_enabled': True,
        'queue_cap_level': 'Medium',
    }


def build_epa_scenario_params():
    """Return conditions for EPA-comparable scenario ($51/ton carbon).

    Uses EPA's social cost of carbon ($51/ton, 2020$) to approximate
    an EPA IPM-like policy environment where carbon has an implicit cost.
    """
    params = build_reference_scenario_params()
    params['name'] = 'CV_Reference_EPA_Carbon'
    params['carbon_price'] = 51
    return params


def build_high_clean_scenario_params():
    """Return conditions approximating the NREL ReEDS Mid-Case.

    ReEDS assumes cost-optimal deployment with RPS constraints, which maps
    roughly to Medium LCOE with moderate carbon pricing and faster learning.
    """
    params = build_reference_scenario_params()
    params['name'] = 'CV_Reference_High_Clean'
    params['carbon_price'] = 30  # Implicit RPS value ~ $30/ton equivalent
    params['learning_rate'] = 'Medium'
    return params


SCENARIO_BUILDERS = {
    'reference_zero_carbon': build_reference_scenario_params,
    'epa_carbon': build_epa_scenario_params,
    'high_clean': build_high_clean_scenario_params,
}


# ---------------------------------------------------------------------------
# 3. Divergence computation
# ---------------------------------------------------------------------------

def compute_divergence_metrics(model_results, reference_data,
                               milestone_years=None):
    """Compare model outputs against a reference trajectory.

    Parameters
    ----------
    model_results : dict
        Model output keyed by year, e.g. {2030: {'clean_share_pct': 55, ...}}.
        Each year value should be a dict containing at least the metric key
        from reference_data['metric'].
    reference_data : dict
        One of AEO_REFERENCE, REEDS_MID, EPA_IPM_REF.
    milestone_years : list[int], optional
        Years at which to compute divergence. Defaults to [2030, 2035, 2040].

    Returns
    -------
    dict with structure:
        {
            'reference': <source string>,
            'metric': <metric name>,
            'milestones': {
                2030: {'model': X, 'reference': Y, 'abs_div': X-Y, 'rel_div_pct': ...},
                ...
            },
            'mean_abs_divergence': float,
            'max_abs_divergence': float,
        }
    """
    if milestone_years is None:
        milestone_years = [2030, 2035, 2040]

    metric = reference_data.get('metric', 'clean_share_pct')
    ref_national = reference_data.get('national', {})

    if not model_results or not ref_national:
        return {
            'reference': reference_data.get('source', 'unknown'),
            'metric': metric,
            'milestones': {},
            'mean_abs_divergence': None,
            'max_abs_divergence': None,
            'error': 'Empty model_results or reference data',
        }

    milestones = {}
    abs_divs = []

    for year in milestone_years:
        ref_val = ref_national.get(year)
        if ref_val is None:
            milestones[year] = {'error': f'No reference value for {year}'}
            continue

        model_year = model_results.get(year) or model_results.get(str(year))
        if model_year is None:
            milestones[year] = {
                'reference': ref_val,
                'error': f'No model result for {year}',
            }
            continue

        # Extract the metric value from model results
        if isinstance(model_year, dict):
            model_val = model_year.get(metric)
        elif isinstance(model_year, (int, float)):
            model_val = model_year
        else:
            milestones[year] = {
                'reference': ref_val,
                'error': f'Unexpected model_year type: {type(model_year).__name__}',
            }
            continue

        if model_val is None:
            milestones[year] = {
                'reference': ref_val,
                'error': f'Metric {metric!r} not found in model results for {year}',
            }
            continue

        abs_div = model_val - ref_val
        rel_div = (abs_div / ref_val * 100) if ref_val != 0 else None

        milestones[year] = {
            'model': round(model_val, 2),
            'reference': ref_val,
            'abs_div': round(abs_div, 2),
            'rel_div_pct': round(rel_div, 2) if rel_div is not None else None,
        }
        abs_divs.append(abs(abs_div))

    return {
        'reference': reference_data.get('source', 'unknown'),
        'metric': metric,
        'milestones': milestones,
        'mean_abs_divergence': round(sum(abs_divs) / len(abs_divs), 2) if abs_divs else None,
        'max_abs_divergence': round(max(abs_divs), 2) if abs_divs else None,
    }


def format_comparison_table(divergences):
    """Format divergence metrics as a markdown table string.

    Parameters
    ----------
    divergences : dict
        Output from compute_divergence_metrics().

    Returns
    -------
    str : Markdown-formatted comparison table.
    """
    ref = divergences.get('reference', 'Unknown')
    metric = divergences.get('metric', 'unknown')
    milestones = divergences.get('milestones', {})

    lines = [
        f"## Cross-Validation: {ref}",
        f"**Metric**: {metric}",
        "",
        "| Year | Model | Reference | Abs Δ | Rel Δ (%) |",
        "|------|-------|-----------|-------|-----------|",
    ]

    for year in sorted(milestones.keys()):
        m = milestones[year]
        if 'error' in m:
            lines.append(f"| {year} | — | {m.get('reference', '—')} | {m['error']} | — |")
        else:
            lines.append(
                f"| {year} | {m['model']} | {m['reference']} "
                f"| {m['abs_div']:+.1f} | {m['rel_div_pct']:+.1f}% |"
            )

    mean_div = divergences.get('mean_abs_divergence')
    max_div = divergences.get('max_abs_divergence')
    lines.append("")
    lines.append(f"**Mean |Δ|**: {mean_div if mean_div is not None else 'N/A'}  "
                 f"**Max |Δ|**: {max_div if max_div is not None else 'N/A'}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 4. Cross-validation runner
# ---------------------------------------------------------------------------

def run_cross_validation(simulation_results, references=None):
    """Run cross-validation comparison against reference trajectories.

    Parameters
    ----------
    simulation_results : dict
        Pre-computed results, structured as:
        {
            'scenarios': {
                'CV_Reference_Zero_Carbon': {
                    'national': {2030: {'clean_share_pct': X, ...}, ...},
                    'by_iso': {
                        'CAISO': {2030: {...}, ...},
                        ...
                    }
                },
                'CV_Reference_EPA_Carbon': { ... },
            }
        }
        Results are passed in — this function does NOT call run_market_simulation().
    references : dict, optional
        Reference trajectories to compare against. Defaults to ALL_REFERENCES.

    Returns
    -------
    dict : Structured comparison results with divergences per scenario × reference.
    """
    if references is None:
        references = ALL_REFERENCES

    scenarios = simulation_results.get('scenarios', {})
    comparisons = {}

    # Map scenarios to their best-match reference
    scenario_reference_pairs = [
        ('CV_Reference_Zero_Carbon', 'AEO_Reference', 'clean_share_pct'),
        ('CV_Reference_Zero_Carbon', 'REEDS_Mid', 'clean_share_pct'),
        ('CV_Reference_EPA_Carbon', 'EPA_IPM_Ref', 'coal_share_pct'),
        ('CV_Reference_High_Clean', 'REEDS_Mid', 'clean_share_pct'),
    ]

    for scenario_name, ref_name, metric in scenario_reference_pairs:
        scenario_data = scenarios.get(scenario_name)
        ref_data = references.get(ref_name)

        if scenario_data is None:
            comparisons[f"{scenario_name}_vs_{ref_name}"] = {
                'error': f'Scenario {scenario_name!r} not found in simulation results',
            }
            continue
        if ref_data is None:
            comparisons[f"{scenario_name}_vs_{ref_name}"] = {
                'error': f'Reference {ref_name!r} not found',
            }
            continue

        pair_key = f"{scenario_name}_vs_{ref_name}"

        # National-level comparison
        national_results = scenario_data.get('national', {})
        comparisons[pair_key] = {
            'national': compute_divergence_metrics(national_results, ref_data),
        }

        # Per-ISO comparison (reference is national, so divergence includes
        # the structural difference between ISO-level and national average)
        by_iso = scenario_data.get('by_iso', {})
        if by_iso:
            iso_comparisons = {}
            for iso in ISOS:
                iso_data = by_iso.get(iso, {})
                if iso_data:
                    iso_comparisons[iso] = compute_divergence_metrics(
                        iso_data, ref_data
                    )
            comparisons[pair_key]['by_iso'] = iso_comparisons

    return {
        'comparisons': comparisons,
        'references_used': list(references.keys()),
        'scenarios_evaluated': list(scenarios.keys()),
    }


def print_cross_validation_report(cv_results):
    """Print a human-readable cross-validation report."""
    comparisons = cv_results.get('comparisons', {})

    print("=" * 72)
    print("CROSS-MODEL VALIDATION REPORT")
    print("=" * 72)

    for pair_name, pair_data in comparisons.items():
        if 'error' in pair_data:
            print(f"\n{pair_name}: {pair_data['error']}")
            continue

        national = pair_data.get('national')
        if national:
            print(f"\n{format_comparison_table(national)}")

        by_iso = pair_data.get('by_iso', {})
        if by_iso:
            print(f"\n### Per-ISO Divergence (vs national reference)")
            for iso in ISOS:
                iso_div = by_iso.get(iso, {})
                mean_div = iso_div.get('mean_abs_divergence')
                if mean_div is not None:
                    print(f"  {iso:6s}: mean |Δ| = {mean_div:.1f} pp")

    print("\n" + "=" * 72)


# ---------------------------------------------------------------------------
# 5. Unit tests — structure validation (no simulation needed)
# ---------------------------------------------------------------------------

class TestCrossValidationStructure(unittest.TestCase):
    """Tests that pass without any simulation data — validates structure only."""

    def test_reference_data_has_required_keys(self):
        """All reference dicts must have source, metric, and national keys."""
        for name, ref in ALL_REFERENCES.items():
            for key in REQUIRED_REFERENCE_KEYS:
                self.assertIn(key, ref,
                              f"Reference {name!r} missing required key {key!r}")

    def test_reference_national_has_milestone_years(self):
        """Each reference trajectory must include at least 2030 and 2040."""
        for name, ref in ALL_REFERENCES.items():
            national = ref['national']
            self.assertIn(2030, national,
                          f"Reference {name!r} missing year 2030")
            self.assertIn(2040, national,
                          f"Reference {name!r} missing year 2040")

    def test_reference_values_are_reasonable(self):
        """Sanity check: all percentage values should be 0-100."""
        for name, ref in ALL_REFERENCES.items():
            for year, val in ref['national'].items():
                self.assertGreaterEqual(val, 0,
                    f"{name} year {year}: value {val} < 0")
                self.assertLessEqual(val, 100,
                    f"{name} year {year}: value {val} > 100")

    def test_build_reference_scenario_params_valid(self):
        """build_reference_scenario_params() returns a dict with required fields."""
        params = build_reference_scenario_params()
        self.assertIsInstance(params, dict)
        self.assertIn('name', params)
        self.assertIn('demand_growth', params)
        self.assertIn('carbon_price', params)
        self.assertEqual(params['carbon_price'], 0)
        self.assertEqual(params['demand_growth'], 'Medium')

    def test_build_epa_scenario_params_has_carbon_price(self):
        """EPA scenario should have $51/ton carbon price."""
        params = build_epa_scenario_params()
        self.assertEqual(params['carbon_price'], 51)
        self.assertNotEqual(params['name'], build_reference_scenario_params()['name'])

    def test_build_high_clean_scenario_params(self):
        """High-clean scenario should have non-zero carbon price."""
        params = build_high_clean_scenario_params()
        self.assertGreater(params['carbon_price'], 0)

    def test_all_scenario_builders_return_valid_dicts(self):
        """Every scenario builder returns a dict with 'name' key."""
        for builder_name, builder_fn in SCENARIO_BUILDERS.items():
            params = builder_fn()
            self.assertIsInstance(params, dict, f"Builder {builder_name!r} didn't return dict")
            self.assertIn('name', params, f"Builder {builder_name!r} missing 'name'")

    def test_compute_divergence_handles_empty_model_results(self):
        """compute_divergence_metrics() should handle empty inputs gracefully."""
        result = compute_divergence_metrics({}, AEO_REFERENCE)
        self.assertIsNotNone(result)
        self.assertIn('error', result)
        self.assertIsNone(result['mean_abs_divergence'])

    def test_compute_divergence_handles_empty_reference(self):
        """compute_divergence_metrics() should handle empty reference data."""
        empty_ref = {'source': 'empty', 'metric': 'x', 'national': {}}
        result = compute_divergence_metrics({2030: {'x': 50}}, empty_ref)
        self.assertIsNotNone(result)
        self.assertIsNone(result['mean_abs_divergence'])

    def test_compute_divergence_with_scalar_model_values(self):
        """compute_divergence_metrics() handles scalar year values (not dicts)."""
        model = {2030: 50, 2035: 55, 2040: 60}
        result = compute_divergence_metrics(model, AEO_REFERENCE)
        self.assertIsNotNone(result)
        self.assertEqual(result['milestones'][2030]['model'], 50)
        self.assertEqual(result['milestones'][2030]['reference'], 47)
        self.assertEqual(result['milestones'][2030]['abs_div'], 3)

    def test_compute_divergence_with_dict_model_values(self):
        """compute_divergence_metrics() handles dict year values."""
        model = {
            2030: {'clean_share_pct': 50},
            2035: {'clean_share_pct': 55},
            2040: {'clean_share_pct': 60},
        }
        result = compute_divergence_metrics(model, AEO_REFERENCE)
        self.assertEqual(result['milestones'][2030]['model'], 50)
        self.assertEqual(result['milestones'][2030]['abs_div'], 3)

    def test_compute_divergence_missing_year_in_model(self):
        """Milestone years missing from model should produce error entries."""
        model = {2030: 50}  # Missing 2035, 2040
        result = compute_divergence_metrics(model, AEO_REFERENCE)
        self.assertIn('error', result['milestones'][2035])
        self.assertIn('error', result['milestones'][2040])

    def test_format_comparison_table_produces_markdown(self):
        """format_comparison_table() returns a string with markdown table."""
        model = {2030: 50, 2035: 55, 2040: 60}
        divs = compute_divergence_metrics(model, AEO_REFERENCE)
        table = format_comparison_table(divs)
        self.assertIsInstance(table, str)
        self.assertIn('|', table)
        self.assertIn('Year', table)
        self.assertIn('Reference', table)

    def test_run_cross_validation_with_empty_results(self):
        """run_cross_validation() handles empty simulation results."""
        result = run_cross_validation({'scenarios': {}})
        self.assertIn('comparisons', result)
        self.assertEqual(result['scenarios_evaluated'], [])

    def test_run_cross_validation_with_mock_data(self):
        """run_cross_validation() processes mock simulation data correctly."""
        mock_results = {
            'scenarios': {
                'CV_Reference_Zero_Carbon': {
                    'national': {
                        2030: {'clean_share_pct': 48},
                        2035: {'clean_share_pct': 53},
                        2040: {'clean_share_pct': 57},
                    },
                    'by_iso': {},
                },
            },
        }
        result = run_cross_validation(mock_results)
        comparisons = result['comparisons']
        # Should have AEO comparison
        aeo_key = 'CV_Reference_Zero_Carbon_vs_AEO_Reference'
        self.assertIn(aeo_key, comparisons)
        national = comparisons[aeo_key]['national']
        self.assertEqual(national['milestones'][2030]['model'], 48)
        self.assertEqual(national['milestones'][2030]['reference'], 47)


# ---------------------------------------------------------------------------
# 6. __main__ — load cached results or print instructions
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    # If run with pytest flags, defer to unittest
    if any(arg in sys.argv for arg in ['-v', '--verbose', '-k', '--tb']):
        unittest.main()
        sys.exit(0)

    print("Cross-Model Validation Script")
    print("-" * 40)

    # Check for cached results
    if CV_RESULTS_PATH.exists():
        print(f"Loading cached results from {CV_RESULTS_PATH}")
        with open(CV_RESULTS_PATH, 'r') as f:
            simulation_results = json.load(f)

        cv_results = run_cross_validation(simulation_results)
        print_cross_validation_report(cv_results)

        # Save comparison report
        report_path = DATA_DIR / 'cv_comparison_report.json'
        with open(report_path, 'w') as f:
            json.dump(cv_results, f, indent=2, default=str)
        print(f"\nReport saved to {report_path}")

    else:
        print(f"\nNo cached results found at:")
        print(f"  {CV_RESULTS_PATH}")
        print(f"\nRun Prompt 5B first to generate simulation results.")
        print(f"The simulation will produce cv_reference_results.json,")
        print(f"then re-run this script to compare against reference trajectories.")

        # Still run structure tests as a sanity check
        print(f"\nRunning structure tests...\n")
        loader = unittest.TestLoader()
        suite = loader.loadTestsFromTestCase(TestCrossValidationStructure)
        runner = unittest.TextTestRunner(verbosity=2)
        result = runner.run(suite)
        sys.exit(0 if result.wasSuccessful() else 1)
