#!/usr/bin/env python3
"""
Cross-Model Validation — Compare market simulator outputs against public reference trajectories.
================================================================================================
Compares our profit-driven market simulation results against published trajectories
from EIA AEO, NREL ReEDS Standard Scenarios, and EPA IPM to validate that the model
produces directionally consistent results under comparable assumptions.

This script is structure-only: no simulations are run. Pre-computed results are
loaded from disk (generated by a separate simulation run).

Usage:
    python -m pytest tests/validate_cross_model.py -v   # Run structure tests
    python tests/validate_cross_model.py                 # Run comparison (needs cached results)
"""

import json
import os
import sys
import unittest
from pathlib import Path

# ---------------------------------------------------------------------------
# 1. Hard-coded reference trajectories from publicly available sources
# ---------------------------------------------------------------------------
# NOTE: These are approximate values transcribed from published reports.
# They should be verified against the actual published tables before use
# in any formal validation. The exact numbers matter less than having the
# comparison structure in place.

AEO_REFERENCE = {
    'source': 'EIA Annual Energy Outlook 2025, Table 8',
    'url': 'https://www.eia.gov/outlooks/aeo/',
    'metric': 'clean_share_pct',  # renewables + nuclear as % of generation
    'national': {2025: 42, 2030: 47, 2035: 51, 2040: 54, 2050: 58},
    # Note: AEO is national, not ISO-specific. Use as directional benchmark.
    # AEO Reference assumes current policy only — no new climate legislation.
}

REEDS_MID = {
    'source': 'NREL Standard Scenarios 2024, Mid-Case',
    'url': 'https://www.nrel.gov/analysis/standard-scenarios.html',
    'metric': 'clean_share_pct',
    'national': {2025: 43, 2030: 52, 2035: 60, 2040: 67, 2050: 78},
    # ReEDS is cost-minimizing with RPS constraints — expect higher clean %
    # than AEO because it assumes cost-optimal deployment, not just current policy.
}

EPA_IPM_REF = {
    'source': 'EPA IPM v6 Reference Case (2023)',
    'url': 'https://www.epa.gov/power-sector-modeling',
    'metric': 'coal_share_pct',
    'national': {2025: 16, 2030: 12, 2035: 8, 2040: 5, 2050: 2},
    # IPM focuses on coal retirement under existing regulations.
    # Useful for validating our fossil dispatch / retirement logic.
}

ALL_REFERENCES = {
    'AEO_Reference': AEO_REFERENCE,
    'REEDS_Mid': REEDS_MID,
    'EPA_IPM_Ref': EPA_IPM_REF,
}

REQUIRED_REFERENCE_KEYS = {'source', 'metric', 'national'}

# ISOs in the market simulator
ISOS = ['CAISO', 'ERCOT', 'PJM', 'NYISO', 'NEISO', 'MISO', 'SPP']

# Default path for cached simulation results
SCRIPT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = SCRIPT_DIR.parent / 'data'
CV_RESULTS_PATH = DATA_DIR / 'cv_reference_results.json'


# ---------------------------------------------------------------------------
# 2. Helper functions — scenario parameter builders
# ---------------------------------------------------------------------------

def build_reference_scenario_params():
    """Return the conditions dict for a 'reference-equivalent' scenario.

    Maps to: Medium demand, Medium LCOE, Medium gas, $0 carbon price.
    This approximates the AEO Reference Case assumptions (current policy,
    no new carbon pricing) within our model's parameter space.
    """
    return {
        'name': 'CV_Reference_Zero_Carbon',
        'demand_growth': 'Medium',
        'lcoe_level': 'Medium',
        'fuel_level': 'Medium',
        'carbon_price': 0,
        'learning_rate': 'Medium',
        '45q_enabled': True,
        'queue_cap_level': 'Medium',
    }


def build_epa_scenario_params():
    """Return conditions for EPA-comparable scenario ($51/ton carbon).

    Uses EPA's social cost of carbon ($51/ton, 2020$) to approximate
    an EPA IPM-like policy environment where carbon has an implicit cost.
    """
    params = build_reference_scenario_params()
    params['name'] = 'CV_Reference_EPA_Carbon'
    params['carbon_price'] = 51
    return params


def build_high_clean_scenario_params():
    """Return conditions approximating the NREL ReEDS Mid-Case.

    ReEDS assumes cost-optimal deployment with RPS constraints, which maps
    roughly to Medium LCOE with moderate carbon pricing and faster learning.
    """
    params = build_reference_scenario_params()
    params['name'] = 'CV_Reference_High_Clean'
    params['carbon_price'] = 30  # Implicit RPS value ~ $30/ton equivalent
    params['learning_rate'] = 'Medium'
    return params


SCENARIO_BUILDERS = {
    'reference_zero_carbon': build_reference_scenario_params,
    'epa_carbon': build_epa_scenario_params,
    'high_clean': build_high_clean_scenario_params,
}


# ---------------------------------------------------------------------------
# 3. Divergence computation
# ---------------------------------------------------------------------------

def compute_divergence_metrics(model_results, reference_data,
                               milestone_years=None):
    """Compare model outputs against a reference trajectory.

    Parameters
    ----------
    model_results : dict
        Model output keyed by year, e.g. {2030: {'clean_share_pct': 55, ...}}.
        Each year value should be a dict containing at least the metric key
        from reference_data['metric'].
    reference_data : dict
        One of AEO_REFERENCE, REEDS_MID, EPA_IPM_REF.
    milestone_years : list[int], optional
        Years at which to compute divergence. Defaults to [2030, 2035, 2040].

    Returns
    -------
    dict with structure:
        {
            'reference': <source string>,
            'metric': <metric name>,
            'milestones': {
                2030: {'model': X, 'reference': Y, 'abs_div': X-Y, 'rel_div_pct': ...},
                ...
            },
            'mean_abs_divergence': float,
            'max_abs_divergence': float,
        }
    """
    if milestone_years is None:
        milestone_years = [2030, 2035, 2040]

    metric = reference_data.get('metric', 'clean_share_pct')
    ref_national = reference_data.get('national', {})

    if not model_results or not ref_national:
        return {
            'reference': reference_data.get('source', 'unknown'),
            'metric': metric,
            'milestones': {},
            'mean_abs_divergence': None,
            'max_abs_divergence': None,
            'error': 'Empty model_results or reference data',
        }

    milestones = {}
    abs_divs = []

    for year in milestone_years:
        ref_val = ref_national.get(year)
        if ref_val is None:
            milestones[year] = {'error': f'No reference value for {year}'}
            continue

        model_year = model_results.get(year) or model_results.get(str(year))
        if model_year is None:
            milestones[year] = {
                'reference': ref_val,
                'error': f'No model result for {year}',
            }
            continue

        # Extract the metric value from model results
        if isinstance(model_year, dict):
            model_val = model_year.get(metric)
        elif isinstance(model_year, (int, float)):
            model_val = model_year
        else:
            milestones[year] = {
                'reference': ref_val,
                'error': f'Unexpected model_year type: {type(model_year).__name__}',
            }
            continue

        if model_val is None:
            milestones[year] = {
                'reference': ref_val,
                'error': f'Metric {metric!r} not found in model results for {year}',
            }
            continue

        abs_div = model_val - ref_val
        rel_div = (abs_div / ref_val * 100) if ref_val != 0 else None

        # Flag divergence as "expected" or "investigate"
        flag = classify_divergence(model_val, ref_val, abs_div,
                                   reference_data, metric)

        milestones[year] = {
            'model': round(model_val, 2),
            'reference': ref_val,
            'abs_div': round(abs_div, 2),
            'rel_div_pct': round(rel_div, 2) if rel_div is not None else None,
            'flag': flag,
        }
        abs_divs.append(abs(abs_div))

    return {
        'reference': reference_data.get('source', 'unknown'),
        'metric': metric,
        'milestones': milestones,
        'mean_abs_divergence': round(sum(abs_divs) / len(abs_divs), 2) if abs_divs else None,
        'max_abs_divergence': round(max(abs_divs), 2) if abs_divs else None,
    }


def classify_divergence(model_val, ref_val, abs_div, reference_data, metric):
    """Classify a divergence as 'expected' or 'investigate' with explanation.

    Rules:
    - Expected: profit-driven model shows lower clean % than cost-minimizing
      models (ReEDS) that assume RPS mandates.
    - Expected: model without policy enforcement retires coal slower than EPA IPM.
    - Investigate: model shows HIGHER clean % than ReEDS (shouldn't happen
      without mandates).
    - Investigate: divergence exceeds 20 percentage points at any milestone.
    """
    source = reference_data.get('source', '')
    is_reeds = 'ReEDS' in source or 'REEDS' in source or 'NREL' in source
    is_epa = 'EPA' in source or 'IPM' in source
    is_aeo = 'AEO' in source or 'EIA' in source

    flags = []

    # Check absolute threshold
    if abs(abs_div) > 20:
        flags.append({
            'status': 'investigate',
            'reason': f'Divergence of {abs_div:+.1f} pp exceeds 20 pp threshold',
        })

    if metric == 'clean_share_pct' or metric == 'clean_pct':
        if is_reeds:
            if model_val < ref_val:
                flags.append({
                    'status': 'expected',
                    'reason': ('Profit-driven model shows lower clean share than '
                               'ReEDS cost-minimizing model with RPS mandates'),
                })
            elif model_val > ref_val:
                flags.append({
                    'status': 'investigate',
                    'reason': ('Model shows HIGHER clean share than ReEDS — '
                               'unexpected without policy mandates'),
                })
        elif is_aeo:
            # AEO is current-policy only — our model could go either way
            if abs(abs_div) <= 10:
                flags.append({
                    'status': 'expected',
                    'reason': 'Within 10 pp of AEO Reference (current policy)',
                })
            elif model_val > ref_val:
                flags.append({
                    'status': 'expected',
                    'reason': ('Model shows higher clean share than AEO — '
                               'plausible if market economics favor renewables'),
                })

    elif metric == 'coal_share_pct':
        if is_epa:
            if model_val > ref_val:
                flags.append({
                    'status': 'expected',
                    'reason': ('Model without policy enforcement retires coal '
                               'slower than EPA IPM regulatory baseline'),
                })
            elif model_val < ref_val:
                flags.append({
                    'status': 'expected',
                    'reason': ('Model retires coal faster than EPA IPM — '
                               'plausible with carbon pricing in scenario'),
                })

    if not flags:
        flags.append({
            'status': 'expected',
            'reason': 'Within normal range for profit-driven vs reference model comparison',
        })

    return flags


def format_comparison_table(divergences):
    """Format divergence metrics as a markdown table string.

    Parameters
    ----------
    divergences : dict
        Output from compute_divergence_metrics().

    Returns
    -------
    str : Markdown-formatted comparison table.
    """
    ref = divergences.get('reference', 'Unknown')
    metric = divergences.get('metric', 'unknown')
    milestones = divergences.get('milestones', {})

    lines = [
        f"## Cross-Validation: {ref}",
        f"**Metric**: {metric}",
        "",
        "| Year | Model | Reference | Abs Δ | Rel Δ (%) |",
        "|------|-------|-----------|-------|-----------|",
    ]

    for year in sorted(milestones.keys()):
        m = milestones[year]
        if 'error' in m:
            lines.append(f"| {year} | — | {m.get('reference', '—')} | {m['error']} | — |")
        else:
            lines.append(
                f"| {year} | {m['model']} | {m['reference']} "
                f"| {m['abs_div']:+.1f} | {m['rel_div_pct']:+.1f}% |"
            )

    mean_div = divergences.get('mean_abs_divergence')
    max_div = divergences.get('max_abs_divergence')
    lines.append("")
    lines.append(f"**Mean |Δ|**: {mean_div if mean_div is not None else 'N/A'}  "
                 f"**Max |Δ|**: {max_div if max_div is not None else 'N/A'}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 4. Cross-validation runner
# ---------------------------------------------------------------------------

def run_cross_validation(simulation_results, references=None):
    """Run cross-validation comparison against reference trajectories.

    Parameters
    ----------
    simulation_results : dict
        Pre-computed results, structured as:
        {
            'scenarios': {
                'CV_Reference_Zero_Carbon': {
                    'national': {2030: {'clean_share_pct': X, ...}, ...},
                    'by_iso': {
                        'CAISO': {2030: {...}, ...},
                        ...
                    }
                },
                'CV_Reference_EPA_Carbon': { ... },
            }
        }
        Results are passed in — this function does NOT call run_market_simulation().
    references : dict, optional
        Reference trajectories to compare against. Defaults to ALL_REFERENCES.

    Returns
    -------
    dict : Structured comparison results with divergences per scenario × reference.
    """
    if references is None:
        references = ALL_REFERENCES

    scenarios = simulation_results.get('scenarios', {})
    comparisons = {}

    # Map scenarios to their best-match reference
    scenario_reference_pairs = [
        ('CV_Reference_Zero_Carbon', 'AEO_Reference', 'clean_share_pct'),
        ('CV_Reference_Zero_Carbon', 'REEDS_Mid', 'clean_share_pct'),
        ('CV_Reference_EPA_Carbon', 'EPA_IPM_Ref', 'coal_share_pct'),
        ('CV_Reference_High_Clean', 'REEDS_Mid', 'clean_share_pct'),
    ]

    for scenario_name, ref_name, metric in scenario_reference_pairs:
        scenario_data = scenarios.get(scenario_name)
        ref_data = references.get(ref_name)

        if scenario_data is None:
            comparisons[f"{scenario_name}_vs_{ref_name}"] = {
                'error': f'Scenario {scenario_name!r} not found in simulation results',
            }
            continue
        if ref_data is None:
            comparisons[f"{scenario_name}_vs_{ref_name}"] = {
                'error': f'Reference {ref_name!r} not found',
            }
            continue

        pair_key = f"{scenario_name}_vs_{ref_name}"

        # National-level comparison
        national_results = scenario_data.get('national', {})
        comparisons[pair_key] = {
            'national': compute_divergence_metrics(national_results, ref_data),
        }

        # Per-ISO comparison (reference is national, so divergence includes
        # the structural difference between ISO-level and national average)
        by_iso = scenario_data.get('by_iso', {})
        if by_iso:
            iso_comparisons = {}
            for iso in ISOS:
                iso_data = by_iso.get(iso, {})
                if iso_data:
                    iso_comparisons[iso] = compute_divergence_metrics(
                        iso_data, ref_data
                    )
            comparisons[pair_key]['by_iso'] = iso_comparisons

    return {
        'comparisons': comparisons,
        'references_used': list(references.keys()),
        'scenarios_evaluated': list(scenarios.keys()),
    }


def print_cross_validation_report(cv_results):
    """Print a human-readable cross-validation report."""
    comparisons = cv_results.get('comparisons', {})

    print("=" * 72)
    print("CROSS-MODEL VALIDATION REPORT")
    print("=" * 72)

    for pair_name, pair_data in comparisons.items():
        if 'error' in pair_data:
            print(f"\n{pair_name}: {pair_data['error']}")
            continue

        national = pair_data.get('national')
        if national:
            print(f"\n{format_comparison_table(national)}")

        by_iso = pair_data.get('by_iso', {})
        if by_iso:
            print(f"\n### Per-ISO Divergence (vs national reference)")
            for iso in ISOS:
                iso_div = by_iso.get(iso, {})
                mean_div = iso_div.get('mean_abs_divergence')
                if mean_div is not None:
                    print(f"  {iso:6s}: mean |Δ| = {mean_div:.1f} pp")

    print("\n" + "=" * 72)


# ---------------------------------------------------------------------------
# 5. Unit tests — structure validation (no simulation needed)
# ---------------------------------------------------------------------------

class TestCrossValidationStructure(unittest.TestCase):
    """Tests that pass without any simulation data — validates structure only."""

    def test_reference_data_has_required_keys(self):
        """All reference dicts must have source, metric, and national keys."""
        for name, ref in ALL_REFERENCES.items():
            for key in REQUIRED_REFERENCE_KEYS:
                self.assertIn(key, ref,
                              f"Reference {name!r} missing required key {key!r}")

    def test_reference_national_has_milestone_years(self):
        """Each reference trajectory must include at least 2030 and 2040."""
        for name, ref in ALL_REFERENCES.items():
            national = ref['national']
            self.assertIn(2030, national,
                          f"Reference {name!r} missing year 2030")
            self.assertIn(2040, national,
                          f"Reference {name!r} missing year 2040")

    def test_reference_values_are_reasonable(self):
        """Sanity check: all percentage values should be 0-100."""
        for name, ref in ALL_REFERENCES.items():
            for year, val in ref['national'].items():
                self.assertGreaterEqual(val, 0,
                    f"{name} year {year}: value {val} < 0")
                self.assertLessEqual(val, 100,
                    f"{name} year {year}: value {val} > 100")

    def test_build_reference_scenario_params_valid(self):
        """build_reference_scenario_params() returns a dict with required fields."""
        params = build_reference_scenario_params()
        self.assertIsInstance(params, dict)
        self.assertIn('name', params)
        self.assertIn('demand_growth', params)
        self.assertIn('carbon_price', params)
        self.assertEqual(params['carbon_price'], 0)
        self.assertEqual(params['demand_growth'], 'Medium')

    def test_build_epa_scenario_params_has_carbon_price(self):
        """EPA scenario should have $51/ton carbon price."""
        params = build_epa_scenario_params()
        self.assertEqual(params['carbon_price'], 51)
        self.assertNotEqual(params['name'], build_reference_scenario_params()['name'])

    def test_build_high_clean_scenario_params(self):
        """High-clean scenario should have non-zero carbon price."""
        params = build_high_clean_scenario_params()
        self.assertGreater(params['carbon_price'], 0)

    def test_all_scenario_builders_return_valid_dicts(self):
        """Every scenario builder returns a dict with 'name' key."""
        for builder_name, builder_fn in SCENARIO_BUILDERS.items():
            params = builder_fn()
            self.assertIsInstance(params, dict, f"Builder {builder_name!r} didn't return dict")
            self.assertIn('name', params, f"Builder {builder_name!r} missing 'name'")

    def test_compute_divergence_handles_empty_model_results(self):
        """compute_divergence_metrics() should handle empty inputs gracefully."""
        result = compute_divergence_metrics({}, AEO_REFERENCE)
        self.assertIsNotNone(result)
        self.assertIn('error', result)
        self.assertIsNone(result['mean_abs_divergence'])

    def test_compute_divergence_handles_empty_reference(self):
        """compute_divergence_metrics() should handle empty reference data."""
        empty_ref = {'source': 'empty', 'metric': 'x', 'national': {}}
        result = compute_divergence_metrics({2030: {'x': 50}}, empty_ref)
        self.assertIsNotNone(result)
        self.assertIsNone(result['mean_abs_divergence'])

    def test_compute_divergence_with_scalar_model_values(self):
        """compute_divergence_metrics() handles scalar year values (not dicts)."""
        model = {2030: 50, 2035: 55, 2040: 60}
        result = compute_divergence_metrics(model, AEO_REFERENCE)
        self.assertIsNotNone(result)
        self.assertEqual(result['milestones'][2030]['model'], 50)
        self.assertEqual(result['milestones'][2030]['reference'], 47)
        self.assertEqual(result['milestones'][2030]['abs_div'], 3)

    def test_compute_divergence_with_dict_model_values(self):
        """compute_divergence_metrics() handles dict year values."""
        model = {
            2030: {'clean_share_pct': 50},
            2035: {'clean_share_pct': 55},
            2040: {'clean_share_pct': 60},
        }
        result = compute_divergence_metrics(model, AEO_REFERENCE)
        self.assertEqual(result['milestones'][2030]['model'], 50)
        self.assertEqual(result['milestones'][2030]['abs_div'], 3)

    def test_compute_divergence_missing_year_in_model(self):
        """Milestone years missing from model should produce error entries."""
        model = {2030: 50}  # Missing 2035, 2040
        result = compute_divergence_metrics(model, AEO_REFERENCE)
        self.assertIn('error', result['milestones'][2035])
        self.assertIn('error', result['milestones'][2040])

    def test_format_comparison_table_produces_markdown(self):
        """format_comparison_table() returns a string with markdown table."""
        model = {2030: 50, 2035: 55, 2040: 60}
        divs = compute_divergence_metrics(model, AEO_REFERENCE)
        table = format_comparison_table(divs)
        self.assertIsInstance(table, str)
        self.assertIn('|', table)
        self.assertIn('Year', table)
        self.assertIn('Reference', table)

    def test_run_cross_validation_with_empty_results(self):
        """run_cross_validation() handles empty simulation results."""
        result = run_cross_validation({'scenarios': {}})
        self.assertIn('comparisons', result)
        self.assertEqual(result['scenarios_evaluated'], [])

    def test_run_cross_validation_with_mock_data(self):
        """run_cross_validation() processes mock simulation data correctly."""
        mock_results = {
            'scenarios': {
                'CV_Reference_Zero_Carbon': {
                    'national': {
                        2030: {'clean_share_pct': 48},
                        2035: {'clean_share_pct': 53},
                        2040: {'clean_share_pct': 57},
                    },
                    'by_iso': {},
                },
            },
        }
        result = run_cross_validation(mock_results)
        comparisons = result['comparisons']
        # Should have AEO comparison
        aeo_key = 'CV_Reference_Zero_Carbon_vs_AEO_Reference'
        self.assertIn(aeo_key, comparisons)
        national = comparisons[aeo_key]['national']
        self.assertEqual(national['milestones'][2030]['model'], 48)
        self.assertEqual(national['milestones'][2030]['reference'], 47)

    def test_classify_divergence_flags_expected(self):
        """classify_divergence() flags lower clean share vs ReEDS as expected."""
        flags = classify_divergence(45, 52, -7, REEDS_MID, 'clean_share_pct')
        statuses = [f['status'] for f in flags]
        self.assertIn('expected', statuses)

    def test_classify_divergence_flags_investigate_higher_than_reeds(self):
        """classify_divergence() flags higher clean share vs ReEDS as investigate."""
        flags = classify_divergence(70, 52, 18, REEDS_MID, 'clean_share_pct')
        statuses = [f['status'] for f in flags]
        self.assertIn('investigate', statuses)

    def test_classify_divergence_flags_investigate_over_20pp(self):
        """classify_divergence() flags >20pp divergence as investigate."""
        flags = classify_divergence(25, 52, -27, REEDS_MID, 'clean_share_pct')
        statuses = [f['status'] for f in flags]
        self.assertIn('investigate', statuses)


# ---------------------------------------------------------------------------
# 6. Cache loading — transform cv_reference_results.json into analysis format
# ---------------------------------------------------------------------------

# Mapping from cache scenario keys to internal scenario names
_CACHE_TO_SCENARIO = {
    'reference': 'CV_Reference_Zero_Carbon',
    'epa_carbon': 'CV_Reference_EPA_Carbon',
    'high_clean': 'CV_Reference_High_Clean',
}


def load_cached_results(path=None):
    """Load cv_reference_results.json and transform to run_cross_validation format.

    The cached file has structure:
        { "reference": { "CAISO": [ {year, clean_pct, ...}, ... ], ... },
          "epa_carbon": { ... } }

    We transform to:
        { "scenarios": {
            "CV_Reference_Zero_Carbon": {
                "national": { 2030: {"clean_share_pct": X}, ... },
                "by_iso": { "CAISO": { 2030: {"clean_share_pct": X}, ... }, ... }
            }, ...
        }}
    """
    if path is None:
        path = CV_RESULTS_PATH
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"Cached results not found: {path}")

    with open(path) as f:
        raw = json.load(f)

    scenarios = {}

    for cache_key, scenario_name in _CACHE_TO_SCENARIO.items():
        scenario_raw = raw.get(cache_key)
        if scenario_raw is None:
            continue

        by_iso = {}
        all_years = {}  # year -> list of clean_pct values (for national avg)

        for iso_name, records in scenario_raw.items():
            if iso_name.startswith('_'):
                continue
            if not isinstance(records, list):
                continue

            iso_by_year = {}
            for rec in records:
                year = rec.get('year')
                if year is None:
                    continue
                clean_pct = rec.get('clean_pct')
                iso_by_year[year] = {
                    'clean_share_pct': clean_pct,
                    'clean_pct': clean_pct,
                    'demand_twh': rec.get('demand_twh'),
                    'emissions_mt': rec.get('emissions_mt'),
                    'emission_rate': rec.get('emission_rate_tco2_mwh'),
                }
                all_years.setdefault(year, []).append(clean_pct)

            by_iso[iso_name] = iso_by_year

        # Compute national average as mean across ISOs
        national = {}
        for year, vals in all_years.items():
            avg = sum(v for v in vals if v is not None) / len(vals) if vals else None
            national[year] = {
                'clean_share_pct': round(avg, 2) if avg is not None else None,
                'clean_pct': round(avg, 2) if avg is not None else None,
            }

        scenarios[scenario_name] = {
            'national': national,
            'by_iso': by_iso,
        }

    return {'scenarios': scenarios}


def run_full_analysis(cached_path=None):
    """Load cached results, run cross-validation, and return structured output.

    Returns (cv_results, iso_divergence_table) where iso_divergence_table is a
    list of dicts suitable for the markdown summary table.
    """
    simulation_results = load_cached_results(cached_path)
    cv_results = run_cross_validation(simulation_results)

    # Build flat ISO × Reference × Year divergence table
    table_rows = []
    comparisons = cv_results.get('comparisons', {})

    for pair_key, pair_data in comparisons.items():
        if 'error' in pair_data:
            continue
        by_iso = pair_data.get('by_iso', {})
        for iso, iso_div in by_iso.items():
            milestones = iso_div.get('milestones', {})
            ref_source = iso_div.get('reference', pair_key)
            for year, m in sorted(milestones.items()):
                if 'error' in m:
                    continue
                flags = m.get('flag', [])
                flag_str = '; '.join(f['reason'] for f in flags)
                status = 'investigate' if any(
                    f['status'] == 'investigate' for f in flags
                ) else 'expected'
                table_rows.append({
                    'pair': pair_key,
                    'iso': iso,
                    'reference': ref_source,
                    'year': year,
                    'model': m.get('model'),
                    'ref_val': m.get('reference'),
                    'abs_div': m.get('abs_div'),
                    'status': status,
                    'explanation': flag_str,
                })

    return cv_results, table_rows


def generate_markdown_report(cv_results, table_rows):
    """Generate the Cross_Validation_Results.md content."""
    lines = [
        "# Cross-Validation Results",
        "",
        "Comparison of the profit-driven market simulator against published reference",
        "trajectories from EIA AEO 2025, NREL ReEDS Standard Scenarios 2024, and EPA IPM v6.",
        "",
        "**Generated from cached simulation results** (`data/cv_reference_results.json`).",
        "No simulations were run to produce this document.",
        "",
        "---",
        "",
        "## Summary Table",
        "",
        "ISO × Reference Model × Milestone Year → Divergence (percentage points)",
        "",
        "| ISO | Comparison | Year | Model (%) | Reference (%) | Divergence (pp) | Status |",
        "|-----|-----------|------|-----------|---------------|-----------------|--------|",
    ]

    for row in sorted(table_rows, key=lambda r: (r['iso'], r['pair'], r['year'])):
        div_str = f"{row['abs_div']:+.1f}" if row['abs_div'] is not None else "N/A"
        lines.append(
            f"| {row['iso']} | {row['pair']} | {row['year']} "
            f"| {row['model']:.1f} | {row['ref_val']} "
            f"| {div_str} | {row['status']} |"
        )

    # Expected divergences
    expected = [r for r in table_rows if r['status'] == 'expected']
    investigate = [r for r in table_rows if r['status'] == 'investigate']

    lines.extend([
        "",
        "---",
        "",
        "## Expected Divergences",
        "",
        "These divergences are consistent with the structural differences between",
        "our profit-driven market simulator and the reference models.",
        "",
    ])

    if expected:
        for row in expected:
            lines.append(
                f"- **{row['iso']} {row['year']}** ({row['pair']}): "
                f"{row['abs_div']:+.1f} pp — {row['explanation']}"
            )
    else:
        lines.append("_No expected divergences recorded._")

    lines.extend([
        "",
        "### Why Profit-Driven ≠ Cost-Minimizing",
        "",
        "Our model simulates **profit-maximizing generator behavior** in competitive",
        "wholesale markets. Generators build or retire based on projected revenue vs.",
        "cost, without a central planner enforcing least-cost outcomes. This differs",
        "from reference models in key ways:",
        "",
        "- **vs. ReEDS (NREL)**: ReEDS is a capacity-expansion model that minimizes",
        "  system-wide cost subject to policy constraints (RPS mandates, clean energy",
        "  standards). It assumes perfect foresight and coordinated deployment. Our",
        "  model's clean share will typically be **lower** because profit-driven",
        "  generators don't internalize policy mandates unless they create direct",
        "  revenue signals (carbon prices, RECs, capacity payments).",
        "",
        "- **vs. AEO (EIA)**: AEO Reference assumes current policy only, making it",
        "  the closest analog to our zero-carbon-price scenario. Divergence should",
        "  be modest (< 10 pp) — differences stem from our use of ISO-specific",
        "  rather than national fuel mixes and our bottom-up generator dispatch.",
        "",
        "- **vs. EPA IPM**: IPM models coal retirement under existing environmental",
        "  regulations. Without explicit policy enforcement, our model may retire",
        "  coal more slowly (profit-driven coal stays online if it covers variable",
        "  costs). With carbon pricing ($51/ton EPA scenario), retirement accelerates.",
        "",
    ])

    lines.extend([
        "---",
        "",
        "## Unexplained Divergences",
        "",
    ])

    if investigate:
        lines.append(
            "The following divergences warrant investigation — they suggest the model"
        )
        lines.append(
            "may be producing results inconsistent with its structural assumptions."
        )
        lines.append("")
        for row in investigate:
            lines.append(
                f"- **{row['iso']} {row['year']}** ({row['pair']}): "
                f"{row['abs_div']:+.1f} pp — {row['explanation']}"
            )
        lines.append("")
        lines.append("### Investigation Notes")
        lines.append("")

        # Group by ISO for investigation notes
        investigate_isos = set(r['iso'] for r in investigate)
        for iso in sorted(investigate_isos):
            iso_rows = [r for r in investigate if r['iso'] == iso]
            max_div = max(abs(r['abs_div']) for r in iso_rows)
            lines.append(f"**{iso}** (max divergence: {max_div:.1f} pp):")
            if any(r['abs_div'] > 0 and 'REEDS' in r['pair'] for r in iso_rows):
                lines.append(
                    f"  - Model shows higher clean share than ReEDS in some years."
                    f" This is unexpected for a profit-driven model without policy"
                    f" mandates. Possible causes: aggressive renewable LCOE"
                    f" assumptions, high capacity factor assumptions, or carbon"
                    f" price scenario creating stronger incentives than ReEDS"
                    f" reference."
                )
            if any(abs(r['abs_div']) > 20 for r in iso_rows):
                lines.append(
                    f"  - Divergence exceeds 20 pp threshold. Review input"
                    f" assumptions (demand growth, LCOE trajectory, fuel prices)"
                    f" for this ISO to verify they align with reference model"
                    f" assumptions."
                )
            lines.append("")
    else:
        lines.append("_No unexplained divergences found. All results are consistent_")
        lines.append("_with expected structural differences between the models._")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## Methodology Note",
        "",
        "### What Divergence Tells Us",
        "",
        "Divergence between our profit-driven model and reference trajectories is",
        "**informative, not diagnostic**. These models answer different questions:",
        "",
        "| Model | Question Answered |",
        "|-------|------------------|",
        "| Our simulator | What do profit-maximizing generators build in competitive markets? |",
        "| NREL ReEDS | What's the least-cost pathway to meet clean energy targets? |",
        "| EIA AEO | What happens under current policy with moderate assumptions? |",
        "| EPA IPM | How do environmental regulations affect coal/gas fleet composition? |",
        "",
        "A **large divergence** doesn't mean either model is wrong — it means the models'",
        "structural assumptions produce different outcomes. Our model lacks policy mandates",
        "(RPS, CES) that drive deployment in ReEDS; conversely, ReEDS doesn't model the",
        "strategic timing and revenue-seeking behavior that shapes real investment decisions.",
        "",
        "### What Divergence Does NOT Tell Us",
        "",
        "- Divergence is NOT a measure of model accuracy (none of these models predict the future).",
        "- Small divergence doesn't validate our model (could be right for wrong reasons).",
        "- Large divergence doesn't invalidate our model (structural differences are expected).",
        "",
        "### Flagging Rules",
        "",
        "- **Expected**: Profit-driven model shows lower clean % than cost-minimizing (ReEDS),",
        "  or retires coal slower than policy-driven (EPA IPM) — consistent with no mandates.",
        "- **Investigate**: Model shows HIGHER clean % than ReEDS (shouldn't happen without",
        "  mandates), or divergence exceeds 20 percentage points at any milestone.",
        "",
    ])

    # National-level summary
    comparisons = cv_results.get('comparisons', {})
    lines.extend(["---", "", "## National-Level Comparisons", ""])
    for pair_key, pair_data in comparisons.items():
        if 'error' in pair_data:
            lines.append(f"### {pair_key}\n\n{pair_data['error']}\n")
            continue
        national = pair_data.get('national')
        if national:
            lines.append(format_comparison_table(national))
            lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 7. Result tests — non-blocking warnings, not failures
# ---------------------------------------------------------------------------

import warnings


class TestCrossValidationResults(unittest.TestCase):
    """Tests that load cached results and run divergence computation.

    Non-blocking: uses warnings instead of assertion failures for divergence
    thresholds, since these reflect model structural differences rather than bugs.
    """

    @classmethod
    def setUpClass(cls):
        """Load cached results and run analysis once for all tests."""
        if not CV_RESULTS_PATH.exists():
            raise unittest.SkipTest(
                f"Cached results not found at {CV_RESULTS_PATH}")
        cls.simulation_results = load_cached_results()
        cls.cv_results = run_cross_validation(cls.simulation_results)
        _, cls.table_rows = run_full_analysis()

    def test_divergence_computed_for_all_isos_and_years(self):
        """Divergence must be computed for all available ISOs × 3 milestone years."""
        comparisons = self.cv_results.get('comparisons', {})
        # Find pairs that have by_iso data
        iso_year_pairs = set()
        for pair_key, pair_data in comparisons.items():
            if 'error' in pair_data:
                continue
            by_iso = pair_data.get('by_iso', {})
            for iso, iso_div in by_iso.items():
                milestones = iso_div.get('milestones', {})
                for year in milestones:
                    if 'error' not in milestones[year]:
                        iso_year_pairs.add((iso, year))

        # We expect at least 3 ISOs × 3 milestone years = 9 pairs
        isos_found = set(p[0] for p in iso_year_pairs)
        years_found = set(p[1] for p in iso_year_pairs)

        self.assertGreaterEqual(len(isos_found), 3,
            f"Expected >= 3 ISOs with divergence data, got {len(isos_found)}: {isos_found}")
        for year in [2030, 2035, 2040]:
            self.assertIn(year, years_found,
                f"Milestone year {year} missing from divergence computation")

    def test_warn_divergence_exceeds_20pp(self):
        """Warn (don't fail) if any divergence exceeds 20 percentage points."""
        large_divs = [
            r for r in self.table_rows
            if r.get('abs_div') is not None and abs(r['abs_div']) > 20
        ]
        if large_divs:
            for r in large_divs:
                warnings.warn(
                    f"Large divergence: {r['iso']} {r['year']} "
                    f"({r['pair']}): {r['abs_div']:+.1f} pp — {r['explanation']}",
                    UserWarning,
                )

    def test_warn_higher_clean_than_reeds(self):
        """Warn if model shows higher clean % than ReEDS Mid-Case."""
        reeds_rows = [
            r for r in self.table_rows
            if 'REEDS' in r.get('pair', '') and r.get('abs_div') is not None
        ]
        higher_than_reeds = [r for r in reeds_rows if r['abs_div'] > 0]
        if higher_than_reeds:
            for r in higher_than_reeds:
                warnings.warn(
                    f"Unexpected: {r['iso']} {r['year']} model clean share "
                    f"({r['model']:.1f}%) exceeds ReEDS ({r['ref_val']}%) "
                    f"by {r['abs_div']:+.1f} pp — profit-driven model shouldn't "
                    f"exceed cost-minimizing with mandates",
                    UserWarning,
                )

    def test_all_rows_have_status(self):
        """Every divergence row should have an expected/investigate classification."""
        for r in self.table_rows:
            self.assertIn(r.get('status'), ('expected', 'investigate'),
                f"Row missing valid status: {r}")


# ---------------------------------------------------------------------------
# 8. __main__ — load cached results, run analysis, generate report
# ---------------------------------------------------------------------------

DOCS_DIR = SCRIPT_DIR.parent / 'docs'


if __name__ == '__main__':
    # If run with pytest flags, defer to unittest
    if any(arg in sys.argv for arg in ['-v', '--verbose', '-k', '--tb']):
        unittest.main()
        sys.exit(0)

    print("Cross-Model Validation Script")
    print("-" * 40)

    # Check for cached results
    if CV_RESULTS_PATH.exists():
        print(f"Loading cached results from {CV_RESULTS_PATH}")

        cv_results, table_rows = run_full_analysis()
        print_cross_validation_report(cv_results)

        # Print ISO-level divergence summary
        print("\n" + "=" * 72)
        print("ISO-LEVEL DIVERGENCE SUMMARY")
        print("=" * 72)
        for row in sorted(table_rows, key=lambda r: (r['iso'], r['year'])):
            status_icon = "!!" if row['status'] == 'investigate' else "OK"
            print(
                f"  [{status_icon}] {row['iso']:6s} {row['year']} "
                f"({row['pair']:40s}): "
                f"model={row['model']:5.1f}%  ref={row['ref_val']:3d}%  "
                f"Δ={row['abs_div']:+6.1f} pp"
            )

        # Save comparison report JSON
        report_path = DATA_DIR / 'cv_comparison_report.json'
        with open(report_path, 'w') as f:
            json.dump(cv_results, f, indent=2, default=str)
        print(f"\nJSON report saved to {report_path}")

        # Generate markdown documentation
        md_content = generate_markdown_report(cv_results, table_rows)
        DOCS_DIR.mkdir(parents=True, exist_ok=True)
        md_path = DOCS_DIR / 'Cross_Validation_Results.md'
        with open(md_path, 'w') as f:
            f.write(md_content)
        print(f"Markdown report saved to {md_path}")

    else:
        print(f"\nNo cached results found at:")
        print(f"  {CV_RESULTS_PATH}")
        print(f"\nRun Prompt 5B first to generate simulation results.")
        print(f"The simulation will produce cv_reference_results.json,")
        print(f"then re-run this script to compare against reference trajectories.")

        # Still run structure tests as a sanity check
        print(f"\nRunning structure tests...\n")
        loader = unittest.TestLoader()
        suite = loader.loadTestsFromTestCase(TestCrossValidationStructure)
        runner = unittest.TextTestRunner(verbosity=2)
        result = runner.run(suite)
        sys.exit(0 if result.wasSuccessful() else 1)
