#!/usr/bin/env python3
"""Step 1D.2: Enhanced storage sweep with lean-mix augmentation.

Fixes a structural bias in the pipeline: Step 1C's near-miss cache only
contains mixes with high base scores (≥90%), which requires ≥139% total
procurement (CAISO). This means the storage sweep only sees "fat" overbuilt
mixes and finds trivial storage amounts, missing the lean+storage frontier
where 60-95pp of overbuilding can be eliminated.

This script:
  1. Loads the near-miss cache from Step 1C (fat mixes, 100k per ISO)
  2. AUGMENTS it with systematically scaled-down "lean" mixes (80-135% total
     procurement) that have lower base scores but high storage potential
  3. Runs the full three-pass adaptive storage sweep with expanded V2 caps
     on the combined pool (fat + lean mixes)

The lean mixes are generated by:
  - Extracting diverse resource archetypes from the near-miss cache
  - Scaling each archetype to target total procurement levels (80-135%)
  - Scoring without storage to get base scores
  - Filtering: keep mixes with base score ≥ 50% (storage can bridge 0-50pp)

Storage capacity caps (V2, 2050-oriented):
  - Battery 4hr:  5.0%  of avg hourly demand (NREL Storage Futures: 200 GW ref)
  - Battery 8hr:  10.0% of avg hourly demand (DOE: 8hr key for deep decarb)
  - LDES:         25.0% of avg hourly demand (DOE LDES Liftoff: 225-460 GW)
  - H2:           25.0% of avg hourly demand (unchanged)

Output: data/step1d2-storage-parquets/{ISO}_t{XX}_storage.parquet

Usage:
  python scripts/step1d2_enhanced_storage.py --iso CAISO
  python scripts/step1d2_enhanced_storage.py --iso PJM --auto-commit
  python scripts/step1d2_enhanced_storage.py --iso ALL
  python scripts/step1d2_enhanced_storage.py --iso ERCOT --thresholds "90,95,99"
"""

import os
import sys

import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

# Import the base modules
import step1d_fine_storage as s1d
import step1_pfs_generator as s1

# ══════════════════════════════════════════════════════════════════════════════
# OVERRIDE CONSTANTS: 2050-oriented storage caps
# ══════════════════════════════════════════════════════════════════════════════

DATA_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), 'data')
V2_OUTPUT_DIR = os.path.join(DATA_DIR, 'step1d2-storage-parquets')

# Pass 0: Maximum storage levels (ceiling screen)
V2_MAX_BAT4 = np.array([5.0], dtype=np.float64)
V2_MAX_BAT8 = np.array([10.0], dtype=np.float64)
V2_MAX_LDES = np.array([25.0], dtype=np.float64)
V2_MAX_H2 = np.array([25.0], dtype=np.float64)

# Pass 1: Extended coarse grids with intermediate points at high end.
V2_FULL_BAT4 = np.array([0, 0.05, 0.1, 0.2, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0],
                         dtype=np.float64)
V2_FULL_BAT8 = np.array([0, 0.1, 0.2, 0.5, 1.0, 2.0, 3.0, 4.0, 6.0, 8.0, 10.0],
                         dtype=np.float64)
V2_FULL_LDES = np.array([0, 0.25, 0.5, 1.0, 2.0, 5.0, 8.0, 12.0, 15.0, 17.0, 21.0, 25.0],
                         dtype=np.float64)
V2_FULL_H2 = np.array([0, 5, 10, 15, 20, 25], dtype=np.float64)

# Wider gap buckets: with higher storage caps, larger gaps are reachable
V2_GAP_BUCKET_PP = [10, 25, 50, 100]

# ══════════════════════════════════════════════════════════════════════════════
# LEAN MIX AUGMENTATION
# ══════════════════════════════════════════════════════════════════════════════

# Scale factors to apply to near-miss archetypes to create lean mixes.
# Each factor produces a copy of each archetype at that total procurement level.
# Range chosen from empirical analysis:
#   - Below 80%: LDES+H2 at max caps cannot bridge the gap (tested CAISO)
#   - 80-100%: lean mixes where storage does most of the heavy lifting
#   - 100-135%: moderate overbuild where storage eliminates the expensive tail
#   - Above 135%: near-miss cache already covers this range
LEAN_SCALE_TARGETS = [80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135]

# Number of diverse archetypes to extract from near-miss cache per ISO.
# More archetypes = better coverage of resource ratio space, but linear cost
# in storage sweep. 200 archetypes × 12 scales = 2,400 lean mixes per ISO.
N_ARCHETYPES = 200

# Minimum base score for a lean mix to be worth running storage sweep on.
# Below 50%, even max storage can't bridge the gap (empirically validated).
LEAN_MIN_BASE_SCORE = 0.50


def _extract_archetypes(combos, n_archetypes):
    """Extract diverse resource archetypes from near-miss combos.

    Uses resource-ratio clustering: normalize each mix to unit sum, then
    pick maximally diverse points by iterative farthest-point sampling.
    This ensures we cover solar-heavy, CF-heavy, wind-heavy, balanced, etc.
    """
    n = len(combos)
    if n <= n_archetypes:
        return np.arange(n)

    # Normalize to resource ratios (unit simplex)
    totals = combos.sum(axis=1, keepdims=True)
    totals = np.maximum(totals, 1e-10)  # avoid div by zero
    ratios = combos / totals

    # Farthest-point sampling for maximal diversity
    selected = [np.random.randint(n)]  # seed with random point
    min_dists = np.full(n, np.inf)

    for _ in range(n_archetypes - 1):
        last = ratios[selected[-1]]
        dists = np.sum((ratios - last) ** 2, axis=1)
        min_dists = np.minimum(min_dists, dists)
        # Zero out already-selected to avoid re-picking
        min_dists[selected] = -1
        next_idx = np.argmax(min_dists)
        selected.append(next_idx)

    return np.array(selected)


def generate_lean_mixes(iso, nm_combos, demand_arr, supply_matrix):
    """Generate lean mixes by scaling near-miss archetypes to lower procurement.

    Returns (lean_combos, lean_scores) — numpy arrays ready to append to
    the near-miss pool. lean_scores are base scores WITHOUT storage.
    """
    rtypes = s1.get_resource_types(iso)
    n_res = len(rtypes)

    # Extract diverse archetypes
    np.random.seed(42)
    arch_idx = _extract_archetypes(nm_combos, N_ARCHETYPES)
    archetypes = nm_combos[arch_idx]
    print(f"  Lean-mix augmentation: {len(archetypes)} archetypes extracted")

    # For each archetype, scale to each target total procurement level
    lean_list = []
    arch_totals = archetypes.sum(axis=1)

    for target_total in LEAN_SCALE_TARGETS:
        for i, arch in enumerate(archetypes):
            orig_total = arch_totals[i]
            if orig_total < 1:
                continue
            scale = target_total / orig_total
            scaled = np.round(arch * scale)
            # Clamp negatives (shouldn't happen but safety)
            scaled = np.maximum(scaled, 0)
            actual_total = scaled.sum()
            if actual_total < 50:  # too small to be useful
                continue
            lean_list.append(scaled)

    if not lean_list:
        print(f"  Lean-mix augmentation: 0 mixes generated")
        return np.empty((0, n_res)), np.empty(0)

    lean_combos = np.array(lean_list, dtype=np.float64)

    # Deduplicate (same rounded mix can appear from different archetypes)
    # Use string hashing for speed
    seen = set()
    unique_idx = []
    for i in range(len(lean_combos)):
        key = tuple(lean_combos[i].astype(int))
        if key not in seen:
            seen.add(key)
            unique_idx.append(i)
    lean_combos = lean_combos[unique_idx]
    print(f"  Lean-mix augmentation: {len(lean_combos):,} unique mixes "
          f"({len(LEAN_SCALE_TARGETS)} scales × {len(archetypes)} archetypes, "
          f"deduped from {len(lean_list):,})")

    # Score without storage
    lean_scores = s1.batch_hourly_scores(demand_arr, supply_matrix, lean_combos)

    # Filter: keep only mixes with reasonable base scores
    keep = lean_scores >= LEAN_MIN_BASE_SCORE
    lean_combos = lean_combos[keep]
    lean_scores = lean_scores[keep]
    print(f"  Lean-mix augmentation: {len(lean_combos):,} mixes with "
          f"base score ≥ {LEAN_MIN_BASE_SCORE*100:.0f}%")

    # Report distribution
    if len(lean_scores) > 0:
        totals = lean_combos.sum(axis=1)
        print(f"    Total procurement: [{totals.min():.0f}%, {totals.max():.0f}%] "
              f"mean={totals.mean():.0f}%")
        print(f"    Base scores: [{lean_scores.min()*100:.1f}%, "
              f"{lean_scores.max()*100:.1f}%] mean={lean_scores.mean()*100:.1f}%")
        for bracket_lo, bracket_hi, label in [
            (50, 80, 'lean (50-80%)'),
            (80, 100, 'mid-lean (80-100%)'),
            (100, 120, 'moderate (100-120%)'),
            (120, 200, 'near-original (120%+)')
        ]:
            mask = (totals >= bracket_lo) & (totals < bracket_hi)
            if mask.any():
                print(f"    {label}: {mask.sum():,} mixes, "
                      f"base score [{lean_scores[mask].min()*100:.1f}%, "
                      f"{lean_scores[mask].max()*100:.1f}%]")

    return lean_combos, lean_scores


def _augmented_load_mixes(original_load_fn):
    """Create a wrapper around load_mixes_with_coarse_fallback that injects lean mixes.

    Returns a function with the same signature that:
    1. Calls the original loader to get fat near-miss mixes
    2. Loads EIA data to score lean mixes
    3. Generates lean mixes and appends them to the pool
    4. Returns the combined pool (forces Pass 0 re-run since lean mixes
       don't have precomputed max_storage_scores)
    """
    def augmented_loader(iso, active_thresholds):
        # 1. Load original near-miss
        nm_combos, nm_scores, nm_max_scores = original_load_fn(iso, active_thresholds)
        if nm_combos is None:
            return None, None, None

        n_original = len(nm_combos)

        # 2. Load EIA profiles for scoring lean mixes
        demand_data, gen_profiles, _, _ = s1.load_data()
        demand_norm = demand_data[iso]['normalized']
        supply_profiles = s1.get_supply_profiles(iso, gen_profiles)
        demand_arr, supply_matrix = s1.prepare_numpy_profiles(
            iso, demand_norm, supply_profiles)

        # 3. Generate lean mixes
        lean_combos, lean_scores = generate_lean_mixes(
            iso, nm_combos, demand_arr, supply_matrix)

        if len(lean_combos) == 0:
            return nm_combos, nm_scores, nm_max_scores

        # 4. Deduplicate against existing near-miss
        nm_keys = set()
        for i in range(len(nm_combos)):
            nm_keys.add(tuple(nm_combos[i].astype(int)))

        new_mask = np.array([
            tuple(lean_combos[i].astype(int)) not in nm_keys
            for i in range(len(lean_combos))
        ], dtype=bool)
        lean_combos = lean_combos[new_mask]
        lean_scores = lean_scores[new_mask]
        n_lean = len(lean_combos)

        if n_lean == 0:
            print(f"  Lean-mix augmentation: all duplicates of existing near-miss")
            return nm_combos, nm_scores, nm_max_scores

        # 5. Combine
        combined_combos = np.vstack([nm_combos, lean_combos])
        combined_scores = np.concatenate([nm_scores, lean_scores])
        print(f"  Combined pool: {n_original:,} original + {n_lean:,} lean = "
              f"{len(combined_combos):,} total mixes")

        # Force Pass 0 re-run (lean mixes don't have max_storage_scores)
        return combined_combos, combined_scores, None

    return augmented_loader


def apply_v2_overrides():
    """Monkey-patch step1d module constants with V2 values + lean-mix augmentation."""
    # Storage cap overrides
    s1d.STEP1D_OUTPUT_DIR = V2_OUTPUT_DIR
    s1d.MAX_BAT4 = V2_MAX_BAT4
    s1d.MAX_BAT8 = V2_MAX_BAT8
    s1d.MAX_LDES = V2_MAX_LDES
    s1d.MAX_H2 = V2_MAX_H2
    s1d.FULL_BAT4 = V2_FULL_BAT4
    s1d.FULL_BAT8 = V2_FULL_BAT8
    s1d.FULL_LDES = V2_FULL_LDES
    s1d.FULL_H2 = V2_FULL_H2
    s1d.GAP_BUCKET_PP = V2_GAP_BUCKET_PP

    # Lean-mix augmentation: override the near-miss loader
    original_loader = s1d.load_mixes_with_coarse_fallback
    s1d.load_mixes_with_coarse_fallback = _augmented_load_mixes(original_loader)

    os.makedirs(V2_OUTPUT_DIR, exist_ok=True)
    print(f"  Step 1D.2 — Enhanced storage + lean-mix augmentation")
    print(f"  Battery 4hr max: {V2_MAX_BAT4[0]}%  (was 0.5%)")
    print(f"  Battery 8hr max: {V2_MAX_BAT8[0]}%  (was 1.0%)")
    print(f"  LDES max:        {V2_MAX_LDES[0]}%  (was 5.0%)")
    print(f"  H2 max:          {V2_MAX_H2[0]}%  (unchanged)")
    print(f"  Lean scales: {LEAN_SCALE_TARGETS}")
    print(f"  Archetypes per ISO: {N_ARCHETYPES}")
    print(f"  Output: {V2_OUTPUT_DIR}")
    print(f"  Coarse grid: bat4={len(V2_FULL_BAT4)} levels, "
          f"bat8={len(V2_FULL_BAT8)}, ldes={len(V2_FULL_LDES)}, "
          f"h2={len(V2_FULL_H2)}")
    print(f"  Total coarse combos (excl H2): "
          f"{len(V2_FULL_BAT4) * len(V2_FULL_BAT8) * len(V2_FULL_LDES)}")
    print()


if __name__ == "__main__":
    apply_v2_overrides()
    s1d.main()
