#!/usr/bin/env python3
"""
Step 7.1F — Extract Strategy 2 Hourly Matching Comparison Data
=============================================================
Reads strategy2_hourly.json (~54MB) and extracts a compact JS data file
for the hourly_comparison.html dashboard page.

Output: dashboard/js/hourly-comparison-data.js
"""

import os
import sys
import json

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)

from pipeline_config import ISOS

INPUT_FILE = os.path.join(ROOT, 'data', 'step5-scenarios', 'strategy2_hourly.json')
OUTPUT_FILE = os.path.join(ROOT, 'dashboard', 'js', 'hourly-comparison-data.js')
STRATEGIES = ['strategy2A', 'strategy2B', 'strategy2C', 'strategy2C_rolloff']
GROWTH = 'Medium'  # Static pages use all-Medium

# Participation levels to include (all available)
PARTICIPATION_LEVELS = [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 90, 100]

# Active thresholds (skip coarse below 50)
ACTIVE_THRESHOLDS = [50, 55, 60, 65, 70, 75, 80, 85, 87.5, 90, 92.5, 95, 97.5, 99, 99.5, 99.9, 99.99]

RESOURCE_KEYS = ['solar', 'wind', 'clean_firm', 'nuclear_uprate', 'battery', 'ldes',
                 'green_h2', 'geothermal', 'existing_merchant', 'sss_allocation',
                 'grid_mix_allocation', 'offshore_wind']


def extract_entry(entry):
    """Extract compact representation of a strategy result entry."""
    rm = entry.get('resource_mix', {})
    md = entry.get('metadata', {})

    # Resource TWh breakdown
    resources = {}
    for k in RESOURCE_KEYS:
        if k in rm and rm[k].get('twh', 0) > 0:
            resources[k] = round(rm[k]['twh'], 2)

    return {
        'y': entry.get('year', 0),
        't': entry.get('threshold', 0),
        'c': round(entry.get('cost_per_mwh', 0), 2),
        'tc': round(entry.get('total_cost_m', 0), 1),
        'co2': round(entry.get('co2_abated_mmt', 0), 3),
        'mac': round(entry.get('mac_per_ton', 0), 2) if entry.get('mac_per_ton') else None,
        'rm': resources,
        'hms': round(md.get('hourly_match_score', 0), 1),
        'curt': round(md.get('curtailment_pct', 0), 1),
        'nb': round(md.get('new_build_twh', 0), 1),
        'nbf': round(md.get('new_build_fraction', 0), 3),
        'fd': round(md.get('fossil_displaced_twh', 0), 1),
        'sss': round(md.get('sss_share_twh', 0), 1),
        'merch': round(md.get('merchant_clean_twh', 0), 1),
        'opr': round(md.get('over_procurement_ratio', 1), 3),
        'bd': round(entry.get('buyer_demand_twh', 0), 1),
        'dd': round(entry.get('demand_twh', 0), 1),
    }


def main():
    print(f"Loading {INPUT_FILE}...")
    with open(INPUT_FILE) as f:
        raw = json.load(f)

    result = {}

    for strat_key in STRATEGIES:
        if strat_key not in raw:
            print(f"  Skipping {strat_key} (not found)")
            continue

        strat_data = raw[strat_key]
        short_key = strat_key.replace('strategy', '')  # '2A', '2B', '2C', '2C_rolloff'
        result[short_key] = {}

        for iso in ISOS:
            if iso not in strat_data:
                continue

            iso_data = strat_data[iso].get(GROWTH, {})
            result[short_key][iso] = {}

            for pct in PARTICIPATION_LEVELS:
                pct_key = f"{pct}pct"
                if pct_key not in iso_data:
                    continue

                entries = iso_data[pct_key]
                # Filter to active thresholds only + threshold 0 (baseline)
                filtered = []
                for e in entries:
                    t = e.get('threshold', 0)
                    if t == 0 or t in ACTIVE_THRESHOLDS:
                        filtered.append(extract_entry(e))

                result[short_key][iso][pct] = filtered

        print(f"  Extracted {short_key}: {len(result[short_key])} ISOs")

    # Write JS file
    js_content = f"// Auto-generated by step9d_extract_hourly_comparison.py\n"
    js_content += f"// Source: strategy2_hourly.json\n"
    js_content += f"const HOURLY_COMPARISON_DATA = {json.dumps(result, separators=(',', ':'))};\n"

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, 'w') as f:
        f.write(js_content)

    size_mb = os.path.getsize(OUTPUT_FILE) / 1024 / 1024
    print(f"\nWrote {OUTPUT_FILE} ({size_mb:.1f} MB)")


if __name__ == '__main__':
    main()
